### ISSUE TITLE
是否可以通过user_id向普通用户和群组定时发送消息呢？

### ISSUE THREAD

**Issue by lion-goose** [scjtqs2/go-tg-tdlib#1]

**Comment by scjtqs2** [comment]
有user_id就行

**Comment by lion-goose** [comment]
> 有user_id就行

{
			"cron": "* * * * *",
			"to_user_name": "@TuringLabbot",
			"text_msg": "/start"
		}
把"to_user_name"换成"user_id"是吗？
我试过，没有成功，我改成了像这样"user_id": "-10047890067",

**Comment by scjtqs2** [comment]
这个不行。你调api吧。chat_id

**Comment by lion-goose** [comment]
> 这个不行。你调api吧。chat_id

呃……API还不会用，不知道怎么再docker-compose里面设置环境变量，没有研究出来……

**Comment by scjtqs2** [comment]
environment 关键字

**Comment by scjtqs2** [comment]
我文档里面应该有docker-compose的运行方式的说明。。

**Comment by lion-goose** [comment]
> 我文档里面应该有docker-compose的运行方式的说明。。

意思是要设置成WebApiStatus: 'true'，启用API才可以在cron.json里面调用user_id，对不

**Comment by scjtqs2** [comment]
api调用是在外面用curl调用。cron.json里面的设置比较有限

api是用curl之类的工具实现。
在宿主机上配置定时任务，例如 crontab 里面配置
`* * * * * curl xxxxx`

**Comment by lion-goose** [comment]
> api调用是在外面用curl调用。cron.json里面的设置比较有限
> 
> 
> 
> api是用curl之类的工具实现。
> 
> 在宿主机上配置定时任务，例如 crontab 里面配置
> 
> `* * * * * curl xxxxx`

噢噢😯，这下明白了，谢谢大哥

**Comment by lion-goose** [comment]
> > api调用是在外面用curl调用。cron.json里面的设置比较有限
> > api是用curl之类的工具实现。
> > 在宿主机上配置定时任务，例如 crontab 里面配置
> > `* * * * * curl xxxxx`
> 
> 噢噢😯，这下明白了，谢谢大哥

大哥，出现了一个新的问题
容器一直自动终止然后重启
[2021-11-22 19:06:25] [INFO]: started ok verison=1.0.0 
tg_bot_1  | Aborted (core dumped)
tg_bot_1  | [2021-11-22 19:07:31] [INFO]: Authorization Ready! Let's rock
然后在data文件夹下，产生了大量的core文件，单个文件100多m，把硬盘一个下午就占满了
找不到哪里出了问题
