### ISSUE TITLE
新注册的tg号无法使用手机号和验证码登录了

### ISSUE THREAD

**Issue by Kaystar** [scjtqs2/go-tg-tdlib#2]
[ERROR]: Error sending auth code : error! code: %!d(float64=406) msg: UPDATE_APP_TO_LOGIN 

如果出现错误码406“UPDATE_APP_TO_LOGIN”，说明TDLib版本已经过时，必须更新到最新的1.7.9版本，原因是Telegram已经迁移到64位标识符，之前的版本不兼容，所以无法使用手机登录（1.7.0 版本仍然可以使用现有帐户和二维码登录）。

大佬能更新吗？

**Comment by scjtqs2** [comment]
行。周末我抽空更新下

**Comment by Kaystar** [comment]
> 行。周末我抽空更新下

谢谢大佬！！！

**Comment by scjtqs2** [comment]
官方的基础库没更新 1.7.10 tag。等他们出1.8.0吧
https://github.com/tdlib/td/issues/1790

**Comment by Kaystar** [comment]
> 官方的基础库没更新 1.7.10 tag。等他们出1.8.0吧 [tdlib/td#1790](https://github.com/tdlib/td/issues/1790)

好的，麻烦了，那只能等了

**Comment by scjtqs2** [comment]
简单做了个 1.7.10的适配。不过由于 tdlib那边基础库没出release，所以是测试版的。
你可以试试
scjtqs/go-tg:1.7.10

**Comment by Kaystar** [comment]
> 简单做了个 1.7.10的适配。不过由于 tdlib那边基础库没出release，所以是测试版的。 你可以试试 scjtqs/go-tg:1.7.10

可以了，成功登录。谢谢！
